Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -22,6 +22,8 @@ jobs:
           - runtime: windows
             os: windows-latest
             reportName: windows-test-report
+    env:
+      TEST_STATUS: success
     steps:
       - name: Configure pagefile
         if: contains(matrix.os, 'windows')
@@ -62,7 +64,11 @@ jobs:
       - name: 'Run UI integration tests'
         id: integration-tests
         working-directory: ./liberty-tools-intellij
-        run: bash ./src/test/resources/ci/scripts/run.sh
+        run: |
+          if ! bash ./src/test/resources/ci/scripts/run.sh; then
+            echo "TEST_STATUS=failed" >> $GITHUB_ENV
+            exit 1
+          fi
       - name: 'Archive Test logs and reports'
         if: ${{ always() }}
         uses: actions/upload-artifact@v3
@@ -73,18 +79,7 @@ jobs:
       - name: 'Slack Notification'
         if: always() # Ensure the notification is sent regardless of job statuses
         run: |
-          if [[ ${{ steps.integration-tests.outcome }} == 'failure' ]]; then
-            STATUS="failed"
-          else
-            STATUS="succeeded"
-          fi
+          STATUS=$([[ $TEST_STATUS == "success" ]] && echo "succeeded" || echo "failed")
           curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"Workflow ${{ github.workflow }} triggered by branch ${{ github.ref }}. PR: ${{ github.event.pull_request.html_url || 'N/A' }}. Build results: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}. Status: $STATUS\"}" $SLACK_WEBHOOK_URL
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-
-
-
-
-
-
-
